---
title: "Untitled"
author: "Ben Derenge"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
#install.packages("aRtsy")

library(aRtsy)
pacman::p_load(dplyr, aRtsy)
```



#palletes

```{r}
colorPalette("random", n=3)

names <- c(
        "blackwhite", "bell", "boogy1", "boogy2", "boogy3", "dark1", "dark2", "dark3", "flora", "gogh", "house", "jasp", "jfa", "jungle",
        "klimt", "kpd", "lava", "nature", "mixer1", "mixer2", "mixer3", "mixer4", "neon1", "neon2", "origami", "retro1", "retro2",
        "retro3", "retro4", "sooph", "sky", "tuscany1", "tuscany2", "tuscany3", "vrolik1", "vrolik2", "vrolik3", "vrolik4", "vrolik5"
      )


name <- sample(names, 1)

rand_pal <- function(){
  names <- c(
        "blackwhite", "bell", "boogy1", "boogy2", "boogy3", "dark1", "dark2", "dark3", "flora", "gogh", "house", "jasp", "jfa", "jungle",
        "klimt", "kpd", "lava", "nature", "mixer1", "mixer2", "mixer3", "mixer4", "neon1", "neon2", "origami", "retro1", "retro2",
        "retro3", "retro4", "sooph", "sky", "tuscany1", "tuscany2", "tuscany3", "vrolik1", "vrolik2", "vrolik3", "vrolik4", "vrolik5"
      )
  t <- sample(names, 1)
  cat(t)
  colorPalette(t)
}

```

```{r}
artwork <- canvas_strokes(colors = c("black", "white"))
saveCanvas(artwork, filename = "myArtwork.png")


canvas_strokes(colors = colorPalette("tuscany1")) %>% saveCanvas("strokes1.png")
canvas_strokes(colors = colorPalette(sample(names, 1)))%>% saveCanvas("strokes2.png")

canvas_collatz(colors = c("red", "blue")) %>% saveCanvas("collatz1.png")

#slow
canvas_forest(colors = colorPalette(sample(names, 1))) %>% saveCanvas("RF1.png")
```



```{r}
aRtsy::canvas_flame(colors = c("#ac80a0", "#89aae6", "#3685b5", "#0471a6", "#061826"))

aRtsy::canvas_flame(colors = colorPalette(sample(names, 1)))
```
```{r}
canvas_turmite(colors = c("#ac80a0", "#89aae6", "#3685b5", "#0471a6", "#061826"))%>% saveCanvas("turmite1.png")



canvas_recaman(colors = c("#1c77c3","#39a9db","#40bcd8","#f39237","#d63230"))  %>% saveCanvas("recaman.png")

canvas_recaman(colors = colorPalette(sample(names, 1)))  %>% saveCanvas("recaman.png")


canvas_turmite(colors = colorPalette("vrolik3")) %>% saveCanvas("turmite2.png")

```


```{r}
{a <- canvas_ribbons(colors = colorPalette("neon1"), background = "#264653", triangle = F) 
a}

saveCanvas(a, "ribbons.png")
```


```{r}
#slow
temp <- canvas_mosaic(colors = colorPalette("retro2"), n = 400)
saveCanvas(temp, "canvas.png")
```

# Functional
```{r}
set.seed(1)
formula <- list(
  x = quote(x_i^2 - sin(y_i^2)),
  y = quote(y_i^3 - cos(x_i^2))
)
canvas_function(colors =rand_pal(),
                by= .01,
                polar = T,
                formula = formula)

{
  canvas_function(colors =rand_pal(),
                by= .1,
                background = "white",
                polar = F,
                formula = list(
  x = quote(y_i),
  y = quote(1/y_i + x_i)
)

)
}
```
```{r}
{
  canvas_function(colors = "black",
                by= .1,
                background = "white",
                polar = T,
                formula = list(
  x = quote(sin(y_i) + x_i),
  y = quote(1/y_i)
)

)
}

canvas_function(colors = rainbow(8), formula = formula) %>% saveCanvas("formula_rainbow.png")
```
#stripes
```{r}
canvas_stripes(colors = colorPalette("random", n = 10))

canvas_stripes(colors = colorPalette("random", n = 10), n =400, H =1, burnin = 100)
```




#Meshes
```{r}
canvas_mesh(color = colorPalette("mixer1"), background = "black")
```

